<a href="https://colab.research.google.com/github/rutvikarnik5/Microsoft-4B-groundwater-timeseries-prediction-using-AI/blob/main/Microsoft_4B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Downloading the Data

In [ ]:
!git clone https://github.com/Break-Through-Tech/Microsoft-4B-groundwater-timeseries-prediction-using-AI.git

Cloning into 'Microsoft-4B-groundwater-timeseries-prediction-using-AI'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 32 (delta 13), reused 7 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (32/32), 7.01 MiB | 9.79 MiB/s, done.
Resolving deltas: 100% (13/13), done.

In [ ]:
%cd Microsoft-4B-groundwater-timeseries-prediction-using-AI

/content/Microsoft-4B-groundwater-timeseries-prediction-using-AI

In [ ]:
%cd notebooks

/content/Microsoft-4B-groundwater-timeseries-prediction-using-AI/notebooks

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Daily Dataset

In [ ]:
df_daily = pd.read_csv("/content/Microsoft-4B-groundwater-timeseries-prediction-using-AI/data/svn_regional_53_wells_daily_2019_2023.csv")
df_daily.head()

/tmp/ipykernel_4953/3712712724.py:1: DtypeWarning: Columns (58) have mixed types. Specify dtype option on import or set low_memory=False.
  df_daily = pd.read_csv("/content/Microsoft-4B-groundwater-timeseries-prediction-using-AI/data/svn_regional_53_wells_daily_2019_2023.csv")

,GROW_ID,interval,date,year,month,aggregated_from_n_values,outliers_change_points,plateaus,groundwater_water_level_elevation_m_asl,precipitation_mswep_mm_year-1,...,permeability_0-100_m_m-2,total_porosity_0-100_m_fraction,soil_texture_0-30_cm_class,soil_texture_30-200_cm_class,soil_saturated_conductivity_0-30_cm_cm_d-1,soil_saturated_conductivity_30-200_cm_cm_d-1,distance_perennial_streams_m,drainage_density_m-1,main_landuse_class,distance_to_cluster_center_km
0,GROW-18108201772,d,2019-01-01,2019,2019-01,NaN,False,0,304.83,45.625,...,3.019952e-11,0.22,Fine,Medium,5.8697,3.4658,4100.0,0.00031,forests_and_natural_vegetation,17.231858
1,GROW-18108201772,d,2019-01-02,2019,2019-01,NaN,False,0,304.79,0.000,...,3.019952e-11,0.22,Fine,Medium,5.8697,3.4658,4100.0,0.00031,forests_and_natural_vegetation,17.231858
2,GROW-18108201772,d,2019-01-03,2019,2019-01,NaN,False,0,304.73,0.000,...,3.019952e-11,0.22,Fine,Medium,5.8697,3.4658,4100.0,0.00031,forests_and_natural_vegetation,17.231858
3,GROW-18108201772,d,2019-01-04,2019,2019-01,NaN,False,0,304.68,0.000,...,3.019952e-11,0.22,Fine,Medium,5.8697,3.4658,4100.0,0.00031,forests_and_natural_vegetation,17.231858
4,GROW-18108201772,d,2019-01-05,2019,2019-01,NaN,False,0,304.64,0.000,...,3.019952e-11,0.22,Fine,Medium,5.8697,3.4658,4100.0,0.00031,forests_and_natural_vegetation,17.231858

In [ ]:
df_daily.shape

(96778, 65)

In [ ]:
df_daily.dtypes

GROW_ID                                          object
interval                                         object
date                                             object
year                                              int64
month                                            object
                                                 ...
soil_saturated_conductivity_30-200_cm_cm_d-1    float64
distance_perennial_streams_m                    float64
drainage_density_m-1                            float64
main_landuse_class                               object
distance_to_cluster_center_km                   float64
Length: 65, dtype: object

In [ ]:
# missing data for daily set

null_counts = df_daily.isnull().sum()
result = null_counts[null_counts > 0]

In [ ]:
nan_col_types = df_daily[result.index].dtypes
nan_col_types

# What data types are missing in the daily dataset?

aggregated_from_n_values                   float64
groundwater_water_level_elevation_m_asl    float64
precipitation_gpcc_mm_year-1               float64
ndvi_ratio                                 float64
withdrawal_industrial_m3_year-1            float64
withdrawal_domestic_m3_year-1              float64
urban_area_fraction                        float64
pastures_fraction                          float64
cropland_rainfed_fraction                  float64
cropland_irrigated_fraction                float64
forests_natural_vegetation_fraction        float64
status                                     float64
aquifer_name                               float64
confinement                                float64
trend_slope_m_year-1                       float64
soil_texture_30-200_cm_class                object
dtype: object

In [ ]:
df_daily = df_daily.drop(columns=['aggregated_from_n_values', 'status', 'aquifer_name', 'confinement'], axis=1)

In [ ]:
dfdaily_missing_cols = df_daily.columns[df_daily.isna().any()]
numeric_cols = df_daily[dfdaily_missing_cols].select_dtypes(include=np.number).columns
df_interpolated = df_daily[numeric_cols].interpolate()
df_daily[numeric_cols] = df_interpolated

In [ ]:
df_daily.columns[df_daily.isna().any()]

Index(['soil_texture_30-200_cm_class'], dtype='object')

In [ ]:
df_daily.shape

(96778, 61)

In [ ]:
# y = groundwater_water_level_elevation_m_asl

In [ ]:
# Identify categorical columns
df_daily.select_dtypes(include=['object'])

,GROW_ID,interval,date,month,name,feature_type,purpose,country,organisation,license,starting_date,ending_date,trend_direction,reference_point,koeppen_geiger_class,hydrobelt_class,aquifer_type_class,soil_texture_0-30_cm_class,soil_texture_30-200_cm_class,main_landuse_class
0,GROW-18108201772,d,2019-01-01,2019-01,Mengeš (Mp-0275),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2004-01-01,2023-12-31,decreasing,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Fine,Medium,forests_and_natural_vegetation
1,GROW-18108201772,d,2019-01-02,2019-01,Mengeš (Mp-0275),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2004-01-01,2023-12-31,decreasing,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Fine,Medium,forests_and_natural_vegetation
2,GROW-18108201772,d,2019-01-03,2019-01,Mengeš (Mp-0275),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2004-01-01,2023-12-31,decreasing,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Fine,Medium,forests_and_natural_vegetation
3,GROW-18108201772,d,2019-01-04,2019-01,Mengeš (Mp-0275),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2004-01-01,2023-12-31,decreasing,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Fine,Medium,forests_and_natural_vegetation
4,GROW-18108201772,d,2019-01-05,2019-01,Mengeš (Mp-0275),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2004-01-01,2023-12-31,decreasing,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Fine,Medium,forests_and_natural_vegetation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96773,GROW-18112547287,d,2023-12-27,2023-12,Lj - Sojerjeva (0631),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2012-01-01,2023-12-31,no trend,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Medium,NaN,forests_and_natural_vegetation
96774,GROW-18112547287,d,2023-12-28,2023-12,Lj - Sojerjeva (0631),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2012-01-01,2023-12-31,no trend,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Medium,NaN,forests_and_natural_vegetation
96775,GROW-18112547287,d,2023-12-29,2023-12,Lj - Sojerjeva (0631),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2012-01-01,2023-12-31,no trend,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Medium,NaN,forests_and_natural_vegetation
96776,GROW-18112547287,d,2023-12-30,2023-12,Lj - Sojerjeva (0631),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2012-01-01,2023-12-31,no trend,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Medium,NaN,forests_and_natural_vegetation
96777,GROW-18112547287,d,2023-12-31,2023-12,Lj - Sojerjeva (0631),Water well,Observation / monitoring,SVN,"Slovenia - MINISTRY OF THE ENVIRONMENT, CLIMAT...",Attribution 4.0 International (CC BY 4.0),2012-01-01,2023-12-31,no trend,Water level elevation a.m.s.l.,Cfb,Mid-latitude,karst,Medium,NaN,forests_and_natural_vegetation

In [ ]:
df_daily[['trend_direction', 'soil_texture_0-30_cm_class', 'soil_texture_30-200_cm_class']].dtypes

trend_direction                 object
soil_texture_0-30_cm_class      object
soil_texture_30-200_cm_class    object
dtype: object

In [ ]:
df_daily['trend_direction'].unique()

array(['decreasing', 'no trend'], dtype=object)

In [ ]:
df_daily['soil_texture_0-30_cm_class'].unique()

array(['Fine', 'Medium'], dtype=object)

In [ ]:
df_daily['soil_texture_30-200_cm_class'].unique()

array(['Medium', nan, 'Fine'], dtype=object)

In [ ]:
df_daily_encoded = df_daily.copy()

In [ ]:
# Columns to encode
to_encode = ['trend_direction', 'soil_texture_0-30_cm_class', 'soil_texture_30-200_cm_class']

for column in to_encode:
  # Create dummy columns
  df_daily_temp = pd.get_dummies(df_daily_encoded[column], prefix=column)

  # Add dummy columns to dataset
  df_daily_encoded = df_daily_encoded.join(df_daily_temp)

  # Drop original column
  df_daily_encoded.drop(columns=column, inplace=True)

# Check whether the loop was successful
df_daily_encoded.columns

Index(['GROW_ID', 'interval', 'date', 'year', 'month',
       'outliers_change_points', 'plateaus',
       'groundwater_water_level_elevation_m_asl',
       'precipitation_mswep_mm_year-1', 'precipitation_gpcc_mm_year-1',
       'potential_evapotranspiration_era5_mm_year-1',
       'potential_evapotranspiration_gleam_mm_year-1',
       'actual_evapotranspiration_mm_year-1', 'interception_mm_year-1',
       'air_temperature_°C', 'snow_depth_m',
       'days_with_snow_cover_days_year-1', 'ndvi_ratio',
       'lai_low_vegetation_ratio', 'lai_high_vegetation_ratio',
       'withdrawal_industrial_m3_year-1', 'withdrawal_domestic_m3_year-1',
       'urban_area_fraction', 'pastures_fraction', 'cropland_rainfed_fraction',
       'cropland_irrigated_fraction', 'forests_natural_vegetation_fraction',
       'original_ID_groundwater', 'name', 'feature_type', 'purpose',
       'latitude', 'longitude', 'country', 'organisation', 'license',
       'starting_date', 'ending_date', 'length_years', 'autocorrelation',
       'gap_fraction', 'trend_slope_m_year-1', 'reference_point',
       'groundwater_mean_m', 'groundwater_median_m', 'koeppen_geiger_class',
       'hydrobelt_class', 'ground_elevation_merit_m_asl',
       'topographic_slope_degree', 'aquifer_type_class',
       'permeability_0-100_m_m-2', 'total_porosity_0-100_m_fraction',
       'soil_saturated_conductivity_0-30_cm_cm_d-1',
       'soil_saturated_conductivity_30-200_cm_cm_d-1',
       'distance_perennial_streams_m', 'drainage_density_m-1',
       'main_landuse_class', 'distance_to_cluster_center_km',
       'trend_direction_decreasing', 'trend_direction_no trend',
       'soil_texture_0-30_cm_class_Fine', 'soil_texture_0-30_cm_class_Medium',
       'soil_texture_30-200_cm_class_Fine',
       'soil_texture_30-200_cm_class_Medium'],
      dtype='object')

# Monthly Dataset

In [ ]:
df_monthly = pd.read_csv("/content/Microsoft-4B-groundwater-timeseries-prediction-using-AI/data/nld_regional_105_wells_2012_2022.csv")
df_monthly.head()

,GROW_ID,interval,date,year,month,aggregated_from_n_values,outliers_change_points,plateaus,groundwater_water_level_elevation_m_asl,precipitation_mswep_mm_year-1,...,aquifer_type_class,permeability_0-100_m_m-2,total_porosity_0-100_m_fraction,soil_texture_0-30_cm_class,soil_texture_30-200_cm_class,soil_saturated_conductivity_0-30_cm_cm_d-1,soil_saturated_conductivity_30-200_cm_cm_d-1,distance_perennial_streams_m,drainage_density_m-1,main_landuse_class
0,GROW-826802686529,MS,2012-01-01,2012,2012-01,NaN,False,0,1.470642,1112.661290,...,porous,3.019952e-11,0.28,Medium,NaN,18.5119,6.4521,4300.0,0.00024,cropland_rainfed
1,GROW-826802686529,MS,2012-02-01,2012,2012-02,NaN,False,0,1.333603,263.523707,...,porous,3.019952e-11,0.28,Medium,NaN,18.5119,6.4521,4300.0,0.00024,cropland_rainfed
2,GROW-826802686529,MS,2012-03-01,2012,2012-03,NaN,False,0,1.323153,246.522177,...,porous,3.019952e-11,0.28,Medium,NaN,18.5119,6.4521,4300.0,0.00024,cropland_rainfed
3,GROW-826802686529,MS,2012-04-01,2012,2012-04,NaN,False,0,1.235456,702.625000,...,porous,3.019952e-11,0.28,Medium,NaN,18.5119,6.4521,4300.0,0.00024,cropland_rainfed
4,GROW-826802686529,MS,2012-05-01,2012,2012-05,NaN,False,0,1.221360,812.419355,...,porous,3.019952e-11,0.28,Medium,NaN,18.5119,6.4521,4300.0,0.00024,cropland_rainfed

In [ ]:
df_monthly.shape

(13860, 64)

In [ ]:
df_monthly.dtypes

GROW_ID                                          object
interval                                         object
date                                             object
year                                              int64
month                                            object
                                                 ...
soil_saturated_conductivity_0-30_cm_cm_d-1      float64
soil_saturated_conductivity_30-200_cm_cm_d-1    float64
distance_perennial_streams_m                    float64
drainage_density_m-1                            float64
main_landuse_class                               object
Length: 64, dtype: object

In [ ]:
# missing data for monthly set

null_counts_monthly = df_monthly.isnull().sum()
result = null_counts_monthly[null_counts_monthly > 0]
result

aggregated_from_n_values                        13860
precipitation_gpcc_mm_year-1                     2520
potential_evapotranspiration_era5_mm_year-1       132
potential_evapotranspiration_gleam_mm_year-1     1380
actual_evapotranspiration_mm_year-1              1380
interception_mm_year-1                           1380
air_temperature_°C                                132
snow_depth_m                                      132
days_with_snow_cover_days_year-1                  132
lai_low_vegetation_ratio                          132
lai_high_vegetation_ratio                         132
withdrawal_industrial_m3_year-1                  1260
withdrawal_domestic_m3_year-1                    1260
urban_area_fraction                              1260
pastures_fraction                                1260
cropland_rainfed_fraction                        1260
cropland_irrigated_fraction                      1260
forests_natural_vegetation_fraction              1260
status                                          13860
aquifer_name                                    13860
confinement                                     13860
trend_slope_m_year-1                             8580
soil_texture_30-200_cm_class                     1320
dtype: int64

In [ ]:
nan_col_types_monthly = df_monthly[result.index].dtypes
nan_col_types_monthly

aggregated_from_n_values                        float64
precipitation_gpcc_mm_year-1                    float64
potential_evapotranspiration_era5_mm_year-1     float64
potential_evapotranspiration_gleam_mm_year-1    float64
actual_evapotranspiration_mm_year-1             float64
interception_mm_year-1                          float64
air_temperature_°C                              float64
snow_depth_m                                    float64
days_with_snow_cover_days_year-1                float64
lai_low_vegetation_ratio                        float64
lai_high_vegetation_ratio                       float64
withdrawal_industrial_m3_year-1                 float64
withdrawal_domestic_m3_year-1                   float64
urban_area_fraction                             float64
pastures_fraction                               float64
cropland_rainfed_fraction                       float64
cropland_irrigated_fraction                     float64
forests_natural_vegetation_fraction             float64
status                                          float64
aquifer_name                                    float64
confinement                                     float64
trend_slope_m_year-1                            float64
soil_texture_30-200_cm_class                     object
dtype: object

In [ ]:
df_monthly = df_monthly.drop(columns=['aggregated_from_n_values', 'status', 'aquifer_name', 'confinement', 'trend_slope_m_year-1'], axis=1)

In [ ]:
dfmonthly_missing_cols = df_monthly.columns[df_monthly.isna().any()]
monthly_cols = df_monthly[dfmonthly_missing_cols].select_dtypes(include=np.number).columns
df_interpolated = df_monthly[monthly_cols].interpolate()
df_monthly[monthly_cols] = df_interpolated

In [ ]:
df_monthly.shape

(13860, 59)

In [ ]:
df_monthly.columns[df_monthly.isna().any()]

Index(['soil_texture_30-200_cm_class'], dtype='object')

In [ ]:
# One-hot encode categorical features, same as df_daily
df_monthly['trend_direction'].unique()

array(['no trend', 'decreasing', 'increasing'], dtype=object)

In [ ]:
df_monthly['soil_texture_0-30_cm_class'].unique()

array(['Medium', 'Coarse', 'Organic'], dtype=object)

In [ ]:
df_monthly['soil_texture_30-200_cm_class'].unique()

array([nan, 'Medium', 'Coarse', 'Fine', 'Organic'], dtype=object)

In [ ]:
df_monthly_encoded = df_monthly.copy()

In [ ]:
for column in to_encode:
  # Create dummy columns
  df_monthly_temp = pd.get_dummies(df_monthly_encoded[column], prefix=column)

  # Add dummy columns to dataset
  df_monthly_encoded = df_monthly_encoded.join(df_monthly_temp)

  # Drop original column
  df_monthly_encoded.drop(columns=column, inplace=True)

# Check whether the loop was successful
df_monthly_encoded.columns

Index(['GROW_ID', 'interval', 'date', 'year', 'month',
       'aggregated_from_n_values', 'outliers_change_points', 'plateaus',
       'groundwater_water_level_elevation_m_asl',
       'precipitation_mswep_mm_year-1', 'precipitation_gpcc_mm_year-1',
       'potential_evapotranspiration_era5_mm_year-1',
       'potential_evapotranspiration_gleam_mm_year-1',
       'actual_evapotranspiration_mm_year-1', 'interception_mm_year-1',
       'air_temperature_°C', 'snow_depth_m',
       'days_with_snow_cover_days_year-1', 'ndvi_ratio',
       'lai_low_vegetation_ratio', 'lai_high_vegetation_ratio',
       'withdrawal_industrial_m3_year-1', 'withdrawal_domestic_m3_year-1',
       'urban_area_fraction', 'pastures_fraction', 'cropland_rainfed_fraction',
       'cropland_irrigated_fraction', 'forests_natural_vegetation_fraction',
       'original_ID_groundwater', 'name', 'feature_type', 'purpose', 'status',
       'latitude', 'longitude', 'country', 'aquifer_name', 'confinement',
       'organisation', 'license', 'starting_date', 'ending_date',
       'length_years', 'autocorrelation', 'gap_fraction',
       'trend_slope_m_year-1', 'reference_point', 'groundwater_mean_m',
       'groundwater_median_m', 'koeppen_geiger_class', 'hydrobelt_class',
       'ground_elevation_merit_m_asl', 'topographic_slope_degree',
       'aquifer_type_class', 'permeability_0-100_m_m-2',
       'total_porosity_0-100_m_fraction',
       'soil_saturated_conductivity_0-30_cm_cm_d-1',
       'soil_saturated_conductivity_30-200_cm_cm_d-1',
       'distance_perennial_streams_m', 'drainage_density_m-1',
       'main_landuse_class', 'trend_direction_decreasing',
       'trend_direction_increasing', 'trend_direction_no trend',
       'soil_texture_0-30_cm_class_Coarse',
       'soil_texture_0-30_cm_class_Medium',
       'soil_texture_0-30_cm_class_Organic',
       'soil_texture_30-200_cm_class_Coarse',
       'soil_texture_30-200_cm_class_Fine',
       'soil_texture_30-200_cm_class_Medium',
       'soil_texture_30-200_cm_class_Organic'],
      dtype='object')